[package]
name = "fdeflate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
miniz_oxide = "0.6.0"

[dependencies]
adler32 = "1.2.0"
