[package]
name = "fdeflate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.12.3"
simd-adler32 = "0.3.4"

[dev-dependencies]
criterion = "0.3"
miniz_oxide = "0.6.0"
rand = "0.8.5"
