# https://embarkstudios.github.io/cargo-deny/

[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
ignore = []

[bans]
multiple-versions = "deny"
deny = []
skip = []
skip-tree = []

[licenses]
unlicensed = "allow"
allow-osi-fsf-free = "either"
copyleft = "allow"